name: Build Docker Images


on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      webui_version:
        description: "Stable Diffusion WebUI version"
        required: false
        default: "1.10.1"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-matrix:
    runs-on: [self-hosted, linux, x64, gpu]
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant:
          - name: "standard"
            dockerfile: "Dockerfile"
            suffix: ""
            build_args: ""
          - name: "cuda"
            dockerfile: "Dockerfile.cuda"
            suffix: "-cuda"
            build_args: ""
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=${{ matrix.variant.suffix }}
            type=ref,event=pr,suffix=${{ matrix.variant.suffix }}
            type=semver,pattern={{version}},suffix=${{ matrix.variant.suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ matrix.variant.suffix }}
            type=semver,pattern={{major}},suffix=${{ matrix.variant.suffix }}
            type=raw,value=latest${{ matrix.variant.suffix }},enable={{is_default_branch}}
            type=raw,value=1.10.1${{ matrix.variant.suffix }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.variant.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant.name }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant.name }}-${{ matrix.platform }}
          build-args: |
            WEBUI_VERSION=${{ github.event.inputs.webui_version || '1.10.1' }}
            ${{ matrix.variant.build_args }}

  build-manifest:
    needs: build-matrix
    runs-on: [self-hosted, linux, x64, gpu]
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant:
          - name: "standard"
            suffix: ""
          - name: "cuda"
            suffix: "-cuda"

    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest${{ matrix.variant.suffix }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest${{ matrix.variant.suffix }}-linux-amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest${{ matrix.variant.suffix }}-linux-arm64
